package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="shopping_mall"
)
public class Address  implements java.io.Serializable {


     private Integer idaddress;
     private City city;
     private District district;
     private PostalCode postalCode;
     private Province province;
     private String addressOne;
     private String addressTwo;
     private Set<User> users = new HashSet<User>(0);

    public Address() {
    }

	
    public Address(City city, District district, PostalCode postalCode, Province province) {
        this.city = city;
        this.district = district;
        this.postalCode = postalCode;
        this.province = province;
    }
    public Address(City city, District district, PostalCode postalCode, Province province, String addressOne, String addressTwo, Set<User> users) {
       this.city = city;
       this.district = district;
       this.postalCode = postalCode;
       this.province = province;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaddress", unique=true, nullable=false)
    public Integer getIdaddress() {
        return this.idaddress;
    }
    
    public void setIdaddress(Integer idaddress) {
        this.idaddress = idaddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_idcity", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_iddistrict", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="postal_code_idpostal_code", nullable=false)
    public PostalCode getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(PostalCode postalCode) {
        this.postalCode = postalCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="province_idprovince", nullable=false)
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }

    
    @Column(name="addressOne")
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }

    
    @Column(name="addressTwo")
    public String getAddressTwo() {
        return this.addressTwo;
    }
    
    public void setAddressTwo(String addressTwo) {
        this.addressTwo = addressTwo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


