package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bidding generated by hbm2java
 */
@Entity
@Table(name="bidding"
    ,catalog="shopping_mall"
)
public class Bidding  implements java.io.Serializable {


     private Integer idbidding;
     private User user;
     private Date bidDate;
     private Date bidForDate;
     private Double winingValue;
     private Set<FronAdImages> fronAdImageses = new HashSet<FronAdImages>(0);

    public Bidding() {
    }

	
    public Bidding(User user) {
        this.user = user;
    }
    public Bidding(User user, Date bidDate, Date bidForDate, Double winingValue, Set<FronAdImages> fronAdImageses) {
       this.user = user;
       this.bidDate = bidDate;
       this.bidForDate = bidForDate;
       this.winingValue = winingValue;
       this.fronAdImageses = fronAdImageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbidding", unique=true, nullable=false)
    public Integer getIdbidding() {
        return this.idbidding;
    }
    
    public void setIdbidding(Integer idbidding) {
        this.idbidding = idbidding;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bid_date", length=10)
    public Date getBidDate() {
        return this.bidDate;
    }
    
    public void setBidDate(Date bidDate) {
        this.bidDate = bidDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bid_for_date", length=10)
    public Date getBidForDate() {
        return this.bidForDate;
    }
    
    public void setBidForDate(Date bidForDate) {
        this.bidForDate = bidForDate;
    }

    
    @Column(name="wining_value", precision=22, scale=0)
    public Double getWiningValue() {
        return this.winingValue;
    }
    
    public void setWiningValue(Double winingValue) {
        this.winingValue = winingValue;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bidding")
    public Set<FronAdImages> getFronAdImageses() {
        return this.fronAdImageses;
    }
    
    public void setFronAdImageses(Set<FronAdImages> fronAdImageses) {
        this.fronAdImageses = fronAdImageses;
    }




}


