package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItems generated by hbm2java
 */
@Entity
@Table(name="cart_items"
    ,catalog="shopping_mall"
)
public class CartItems  implements java.io.Serializable {


     private Integer idCartItems;
     private Cart cart;
     private Stock stock;
     private Integer qty;

    public CartItems() {
    }

	
    public CartItems(Cart cart, Stock stock) {
        this.cart = cart;
        this.stock = stock;
    }
    public CartItems(Cart cart, Stock stock, Integer qty) {
       this.cart = cart;
       this.stock = stock;
       this.qty = qty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cart_items", unique=true, nullable=false)
    public Integer getIdCartItems() {
        return this.idCartItems;
    }
    
    public void setIdCartItems(Integer idCartItems) {
        this.idCartItems = idCartItems;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_idcart", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_idstock", nullable=false)
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


