package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catogaries generated by hbm2java
 */
@Entity
@Table(name="catogaries"
    ,catalog="shopping_mall"
)
public class Catogaries  implements java.io.Serializable {


     private Integer idcatogaries;
     private String catogariName;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<SubCatogary> subCatogaries = new HashSet<SubCatogary>(0);

    public Catogaries() {
    }

    public Catogaries(String catogariName, Set<Stock> stocks, Set<SubCatogary> subCatogaries) {
       this.catogariName = catogariName;
       this.stocks = stocks;
       this.subCatogaries = subCatogaries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcatogaries", unique=true, nullable=false)
    public Integer getIdcatogaries() {
        return this.idcatogaries;
    }
    
    public void setIdcatogaries(Integer idcatogaries) {
        this.idcatogaries = idcatogaries;
    }

    
    @Column(name="catogari_name")
    public String getCatogariName() {
        return this.catogariName;
    }
    
    public void setCatogariName(String catogariName) {
        this.catogariName = catogariName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catogaries")
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catogaries")
    public Set<SubCatogary> getSubCatogaries() {
        return this.subCatogaries;
    }
    
    public void setSubCatogaries(Set<SubCatogary> subCatogaries) {
        this.subCatogaries = subCatogaries;
    }




}


