package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name="chat"
    ,catalog="shopping_mall"
)
public class Chat  implements java.io.Serializable {


     private Integer idchat;
     private User user;
     private Integer recieverId;
     private String message;
     private String subject;
     private Integer status;
     private Date date;

    public Chat() {
    }

	
    public Chat(User user) {
        this.user = user;
    }
    public Chat(User user, Integer recieverId, String message, String subject, Integer status, Date date) {
       this.user = user;
       this.recieverId = recieverId;
       this.message = message;
       this.subject = subject;
       this.status = status;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idchat", unique=true, nullable=false)
    public Integer getIdchat() {
        return this.idchat;
    }
    
    public void setIdchat(Integer idchat) {
        this.idchat = idchat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="reciever_id")
    public Integer getRecieverId() {
        return this.recieverId;
    }
    
    public void setRecieverId(Integer recieverId) {
        this.recieverId = recieverId;
    }

    
    @Column(name="message", length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


