package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
    ,catalog="shopping_mall"
)
public class District  implements java.io.Serializable {


     private Integer iddistrict;
     private Province province;
     private String districtName;
     private Set<Address> addresses = new HashSet<Address>(0);
     private Set<City> cities = new HashSet<City>(0);

    public District() {
    }

	
    public District(Province province) {
        this.province = province;
    }
    public District(Province province, String districtName, Set<Address> addresses, Set<City> cities) {
       this.province = province;
       this.districtName = districtName;
       this.addresses = addresses;
       this.cities = cities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddistrict", unique=true, nullable=false)
    public Integer getIddistrict() {
        return this.iddistrict;
    }
    
    public void setIddistrict(Integer iddistrict) {
        this.iddistrict = iddistrict;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="province_idprovince", nullable=false)
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }

    
    @Column(name="district_name")
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }




}


