package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailConfirmation generated by hbm2java
 */
@Entity
@Table(name="email_confirmation"
    ,catalog="shopping_mall"
)
public class EmailConfirmation  implements java.io.Serializable {


     private Integer idemailConfirmation;
     private User user;
     private String generatodCode;

    public EmailConfirmation() {
    }

	
    public EmailConfirmation(User user) {
        this.user = user;
    }
    public EmailConfirmation(User user, String generatodCode) {
       this.user = user;
       this.generatodCode = generatodCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemail_confirmation", unique=true, nullable=false)
    public Integer getIdemailConfirmation() {
        return this.idemailConfirmation;
    }
    
    public void setIdemailConfirmation(Integer idemailConfirmation) {
        this.idemailConfirmation = idemailConfirmation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="generatod_code")
    public String getGeneratodCode() {
        return this.generatodCode;
    }
    
    public void setGeneratodCode(String generatodCode) {
        this.generatodCode = generatodCode;
    }




}


