package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FronAdImages generated by hbm2java
 */
@Entity
@Table(name="fron_ad_images"
    ,catalog="shopping_mall"
)
public class FronAdImages  implements java.io.Serializable {


     private Integer fronAdImagesId;
     private Bidding bidding;
     private String imgPath;
     private String adDescription;

    public FronAdImages() {
    }

	
    public FronAdImages(Bidding bidding) {
        this.bidding = bidding;
    }
    public FronAdImages(Bidding bidding, String imgPath, String adDescription) {
       this.bidding = bidding;
       this.imgPath = imgPath;
       this.adDescription = adDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fron_ad_images_id", unique=true, nullable=false)
    public Integer getFronAdImagesId() {
        return this.fronAdImagesId;
    }
    
    public void setFronAdImagesId(Integer fronAdImagesId) {
        this.fronAdImagesId = fronAdImagesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bidding_idbidding", nullable=false)
    public Bidding getBidding() {
        return this.bidding;
    }
    
    public void setBidding(Bidding bidding) {
        this.bidding = bidding;
    }

    
    @Column(name="img_path", length=225)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    
    @Column(name="ad_description", length=65535)
    public String getAdDescription() {
        return this.adDescription;
    }
    
    public void setAdDescription(String adDescription) {
        this.adDescription = adDescription;
    }




}


