package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Interfaces generated by hbm2java
 */
@Entity
@Table(name="interfaces"
    ,catalog="shopping_mall"
)
public class Interfaces  implements java.io.Serializable {


     private Integer idinterfaces;
     private String interfaceName;
     private Set<Privilages> privilageses = new HashSet<Privilages>(0);

    public Interfaces() {
    }

    public Interfaces(String interfaceName, Set<Privilages> privilageses) {
       this.interfaceName = interfaceName;
       this.privilageses = privilageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinterfaces", unique=true, nullable=false)
    public Integer getIdinterfaces() {
        return this.idinterfaces;
    }
    
    public void setIdinterfaces(Integer idinterfaces) {
        this.idinterfaces = idinterfaces;
    }

    
    @Column(name="interface_name")
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="interfaces")
    public Set<Privilages> getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set<Privilages> privilageses) {
        this.privilageses = privilageses;
    }




}


