package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="shopping_mall"
)
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private User user;
     private Integer requestedQty;
     private Set<StockHasInvoice> stockHasInvoices = new HashSet<StockHasInvoice>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Integer requestedQty, Set<StockHasInvoice> stockHasInvoices) {
       this.user = user;
       this.requestedQty = requestedQty;
       this.stockHasInvoices = stockHasInvoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinvoice", unique=true, nullable=false)
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="requested_qty")
    public Integer getRequestedQty() {
        return this.requestedQty;
    }
    
    public void setRequestedQty(Integer requestedQty) {
        this.requestedQty = requestedQty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invoice")
    public Set<StockHasInvoice> getStockHasInvoices() {
        return this.stockHasInvoices;
    }
    
    public void setStockHasInvoices(Set<StockHasInvoice> stockHasInvoices) {
        this.stockHasInvoices = stockHasInvoices;
    }




}


