package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginSession generated by hbm2java
 */
@Entity
@Table(name="login_session"
    ,catalog="shopping_mall"
)
public class LoginSession  implements java.io.Serializable {


     private Integer idloginSession;
     private UserLogin userLogin;
     private Date loginSessionintime;
     private Date loginSessionouttime;
     private String ipAddress;
     private Set<SessionActivity> sessionActivities = new HashSet<SessionActivity>(0);

    public LoginSession() {
    }

	
    public LoginSession(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public LoginSession(UserLogin userLogin, Date loginSessionintime, Date loginSessionouttime, String ipAddress, Set<SessionActivity> sessionActivities) {
       this.userLogin = userLogin;
       this.loginSessionintime = loginSessionintime;
       this.loginSessionouttime = loginSessionouttime;
       this.ipAddress = ipAddress;
       this.sessionActivities = sessionActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idlogin_session", unique=true, nullable=false)
    public Integer getIdloginSession() {
        return this.idloginSession;
    }
    
    public void setIdloginSession(Integer idloginSession) {
        this.idloginSession = idloginSession;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_login_iduser_login", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="login_sessionintime", length=19)
    public Date getLoginSessionintime() {
        return this.loginSessionintime;
    }
    
    public void setLoginSessionintime(Date loginSessionintime) {
        this.loginSessionintime = loginSessionintime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="login_sessionouttime", length=19)
    public Date getLoginSessionouttime() {
        return this.loginSessionouttime;
    }
    
    public void setLoginSessionouttime(Date loginSessionouttime) {
        this.loginSessionouttime = loginSessionouttime;
    }

    
    @Column(name="ip_address")
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loginSession")
    public Set<SessionActivity> getSessionActivities() {
        return this.sessionActivities;
    }
    
    public void setSessionActivities(Set<SessionActivity> sessionActivities) {
        this.sessionActivities = sessionActivities;
    }




}


