package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersHasStock generated by hbm2java
 */
@Entity
@Table(name="orders_has_stock"
    ,catalog="shopping_mall"
)
public class OrdersHasStock  implements java.io.Serializable {


     private Integer ordersHasStockid;
     private Orders orders;
     private Stock stock;

    public OrdersHasStock() {
    }

    public OrdersHasStock(Orders orders, Stock stock) {
       this.orders = orders;
       this.stock = stock;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="orders_has_stockid", unique=true, nullable=false)
    public Integer getOrdersHasStockid() {
        return this.ordersHasStockid;
    }
    
    public void setOrdersHasStockid(Integer ordersHasStockid) {
        this.ordersHasStockid = ordersHasStockid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orders_idorders", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_idstock", nullable=false)
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }




}


