package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="shopping_mall"
)
public class Orders  implements java.io.Serializable {


     private Integer idorders;
     private Paymanetmethod paymanetmethod;
     private Shops shops;
     private User user;
     private Integer qty;
     private String address;
     private String message;
     private Integer status;
     private Set<OrdersHasStock> ordersHasStocks = new HashSet<OrdersHasStock>(0);

    public Orders() {
    }

	
    public Orders(Paymanetmethod paymanetmethod, Shops shops, User user) {
        this.paymanetmethod = paymanetmethod;
        this.shops = shops;
        this.user = user;
    }
    public Orders(Paymanetmethod paymanetmethod, Shops shops, User user, Integer qty, String address, String message, Integer status, Set<OrdersHasStock> ordersHasStocks) {
       this.paymanetmethod = paymanetmethod;
       this.shops = shops;
       this.user = user;
       this.qty = qty;
       this.address = address;
       this.message = message;
       this.status = status;
       this.ordersHasStocks = ordersHasStocks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idorders", unique=true, nullable=false)
    public Integer getIdorders() {
        return this.idorders;
    }
    
    public void setIdorders(Integer idorders) {
        this.idorders = idorders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paymanetMethod_idpaymanetMethod", nullable=false)
    public Paymanetmethod getPaymanetmethod() {
        return this.paymanetmethod;
    }
    
    public void setPaymanetmethod(Paymanetmethod paymanetmethod) {
        this.paymanetmethod = paymanetmethod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shops_idShops", nullable=false)
    public Shops getShops() {
        return this.shops;
    }
    
    public void setShops(Shops shops) {
        this.shops = shops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="address", length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="message", length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrdersHasStock> getOrdersHasStocks() {
        return this.ordersHasStocks;
    }
    
    public void setOrdersHasStocks(Set<OrdersHasStock> ordersHasStocks) {
        this.ordersHasStocks = ordersHasStocks;
    }




}


