package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ownership generated by hbm2java
 */
@Entity
@Table(name="ownership"
    ,catalog="shopping_mall"
)
public class Ownership  implements java.io.Serializable {


     private Integer shopsHasUserId;
     private Shops shops;
     private User user;

    public Ownership() {
    }

    public Ownership(Shops shops, User user) {
       this.shops = shops;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Shops_has_user_id", unique=true, nullable=false)
    public Integer getShopsHasUserId() {
        return this.shopsHasUserId;
    }
    
    public void setShopsHasUserId(Integer shopsHasUserId) {
        this.shopsHasUserId = shopsHasUserId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Shops_idShops", nullable=false)
    public Shops getShops() {
        return this.shops;
    }
    
    public void setShops(Shops shops) {
        this.shops = shops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


