package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paymanetmethod generated by hbm2java
 */
@Entity
@Table(name="paymanetmethod"
    ,catalog="shopping_mall"
)
public class Paymanetmethod  implements java.io.Serializable {


     private Integer idpaymanetMethod;
     private String method;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Paymanetmethod() {
    }

    public Paymanetmethod(String method, Set<Orders> orderses) {
       this.method = method;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpaymanetMethod", unique=true, nullable=false)
    public Integer getIdpaymanetMethod() {
        return this.idpaymanetMethod;
    }
    
    public void setIdpaymanetMethod(Integer idpaymanetMethod) {
        this.idpaymanetMethod = idpaymanetMethod;
    }

    
    @Column(name="method", length=45)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymanetmethod")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


