package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShopsHasStock generated by hbm2java
 */
@Entity
@Table(name="shops_has_stock"
    ,catalog="shopping_mall"
)
public class ShopsHasStock  implements java.io.Serializable {


     private Integer shopsHasStockId;
     private Shops shops;
     private Stock stock;

    public ShopsHasStock() {
    }

    public ShopsHasStock(Shops shops, Stock stock) {
       this.shops = shops;
       this.stock = stock;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Shops_has_stock_id", unique=true, nullable=false)
    public Integer getShopsHasStockId() {
        return this.shopsHasStockId;
    }
    
    public void setShopsHasStockId(Integer shopsHasStockId) {
        this.shopsHasStockId = shopsHasStockId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Shops_idShops", nullable=false)
    public Shops getShops() {
        return this.shops;
    }
    
    public void setShops(Shops shops) {
        this.shops = shops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_idstock", nullable=false)
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }




}


