package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shops generated by hbm2java
 */
@Entity
@Table(name="shops"
    ,catalog="shopping_mall"
)
public class Shops  implements java.io.Serializable {


     private Integer idShops;
     private ShopType shopType;
     private String sname;
     private String saddress;
     private Integer status;
     private Set<Subcription> subcriptions = new HashSet<Subcription>(0);
     private Set<Ownership> ownerships = new HashSet<Ownership>(0);
     private Set<ShopsHasStock> shopsHasStocks = new HashSet<ShopsHasStock>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Shops() {
    }

	
    public Shops(ShopType shopType) {
        this.shopType = shopType;
    }
    public Shops(ShopType shopType, String sname, String saddress, Integer status, Set<Subcription> subcriptions, Set<Ownership> ownerships, Set<ShopsHasStock> shopsHasStocks, Set<Orders> orderses) {
       this.shopType = shopType;
       this.sname = sname;
       this.saddress = saddress;
       this.status = status;
       this.subcriptions = subcriptions;
       this.ownerships = ownerships;
       this.shopsHasStocks = shopsHasStocks;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idShops", unique=true, nullable=false)
    public Integer getIdShops() {
        return this.idShops;
    }
    
    public void setIdShops(Integer idShops) {
        this.idShops = idShops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shop_type_idshop_type", nullable=false)
    public ShopType getShopType() {
        return this.shopType;
    }
    
    public void setShopType(ShopType shopType) {
        this.shopType = shopType;
    }

    
    @Column(name="sname")
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }

    
    @Column(name="saddress", length=65535)
    public String getSaddress() {
        return this.saddress;
    }
    
    public void setSaddress(String saddress) {
        this.saddress = saddress;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shops")
    public Set<Subcription> getSubcriptions() {
        return this.subcriptions;
    }
    
    public void setSubcriptions(Set<Subcription> subcriptions) {
        this.subcriptions = subcriptions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shops")
    public Set<Ownership> getOwnerships() {
        return this.ownerships;
    }
    
    public void setOwnerships(Set<Ownership> ownerships) {
        this.ownerships = ownerships;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shops")
    public Set<ShopsHasStock> getShopsHasStocks() {
        return this.shopsHasStocks;
    }
    
    public void setShopsHasStocks(Set<ShopsHasStock> shopsHasStocks) {
        this.shopsHasStocks = shopsHasStocks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shops")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


