package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopType generated by hbm2java
 */
@Entity
@Table(name="shop_type"
    ,catalog="shopping_mall"
)
public class ShopType  implements java.io.Serializable {


     private Integer idshopType;
     private String typeName;
     private Set<Shops> shopses = new HashSet<Shops>(0);

    public ShopType() {
    }

    public ShopType(String typeName, Set<Shops> shopses) {
       this.typeName = typeName;
       this.shopses = shopses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idshop_type", unique=true, nullable=false)
    public Integer getIdshopType() {
        return this.idshopType;
    }
    
    public void setIdshopType(Integer idshopType) {
        this.idshopType = idshopType;
    }

    
    @Column(name="TYPE_NAME")
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shopType")
    public Set<Shops> getShopses() {
        return this.shopses;
    }
    
    public void setShopses(Set<Shops> shopses) {
        this.shopses = shopses;
    }




}


