package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubCatogary generated by hbm2java
 */
@Entity
@Table(name="sub_catogary"
    ,catalog="shopping_mall"
)
public class SubCatogary  implements java.io.Serializable {


     private Integer idSubCatogary;
     private Catogaries catogaries;
     private String subCatogaryName;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public SubCatogary() {
    }

	
    public SubCatogary(Catogaries catogaries) {
        this.catogaries = catogaries;
    }
    public SubCatogary(Catogaries catogaries, String subCatogaryName, Set<Stock> stocks) {
       this.catogaries = catogaries;
       this.subCatogaryName = subCatogaryName;
       this.stocks = stocks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSub_catogary", unique=true, nullable=false)
    public Integer getIdSubCatogary() {
        return this.idSubCatogary;
    }
    
    public void setIdSubCatogary(Integer idSubCatogary) {
        this.idSubCatogary = idSubCatogary;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catogaries_idcatogaries", nullable=false)
    public Catogaries getCatogaries() {
        return this.catogaries;
    }
    
    public void setCatogaries(Catogaries catogaries) {
        this.catogaries = catogaries;
    }

    
    @Column(name="Sub_catogary_name")
    public String getSubCatogaryName() {
        return this.subCatogaryName;
    }
    
    public void setSubCatogaryName(String subCatogaryName) {
        this.subCatogaryName = subCatogaryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCatogary")
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


