package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subcription generated by hbm2java
 */
@Entity
@Table(name="subcription"
    ,catalog="shopping_mall"
)
public class Subcription  implements java.io.Serializable {


     private Integer subsId;
     private Shops shops;
     private User user;
     private Set<SubcriptionHasStock> subcriptionHasStocks = new HashSet<SubcriptionHasStock>(0);

    public Subcription() {
    }

	
    public Subcription(Shops shops, User user) {
        this.shops = shops;
        this.user = user;
    }
    public Subcription(Shops shops, User user, Set<SubcriptionHasStock> subcriptionHasStocks) {
       this.shops = shops;
       this.user = user;
       this.subcriptionHasStocks = subcriptionHasStocks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subs_id", unique=true, nullable=false)
    public Integer getSubsId() {
        return this.subsId;
    }
    
    public void setSubsId(Integer subsId) {
        this.subsId = subsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Shops_idShops", nullable=false)
    public Shops getShops() {
        return this.shops;
    }
    
    public void setShops(Shops shops) {
        this.shops = shops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subcription")
    public Set<SubcriptionHasStock> getSubcriptionHasStocks() {
        return this.subcriptionHasStocks;
    }
    
    public void setSubcriptionHasStocks(Set<SubcriptionHasStock> subcriptionHasStocks) {
        this.subcriptionHasStocks = subcriptionHasStocks;
    }




}


