package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="user_role"
    ,catalog="shopping_mall"
)
public class UserRole  implements java.io.Serializable {


     private Integer iduserRole;
     private String roleName;
     private Set<UserRoleHasUseCase> userRoleHasUseCases = new HashSet<UserRoleHasUseCase>(0);
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);

    public UserRole() {
    }

    public UserRole(String roleName, Set<UserRoleHasUseCase> userRoleHasUseCases, Set<UserLogin> userLogins) {
       this.roleName = roleName;
       this.userRoleHasUseCases = userRoleHasUseCases;
       this.userLogins = userLogins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser_role", unique=true, nullable=false)
    public Integer getIduserRole() {
        return this.iduserRole;
    }
    
    public void setIduserRole(Integer iduserRole) {
        this.iduserRole = iduserRole;
    }

    
    @Column(name="role_name")
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRole")
    public Set<UserRoleHasUseCase> getUserRoleHasUseCases() {
        return this.userRoleHasUseCases;
    }
    
    public void setUserRoleHasUseCases(Set<UserRoleHasUseCase> userRoleHasUseCases) {
        this.userRoleHasUseCases = userRoleHasUseCases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRole")
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }




}


