package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name="user_login"
    ,catalog="shopping_mall"
)
public class UserLogin  implements java.io.Serializable {


     private Integer iduserLogin;
     private User user;
     private UserRole userRole;
     private String email;
     private String password;
     private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);

    public UserLogin() {
    }

	
    public UserLogin(User user, UserRole userRole) {
        this.user = user;
        this.userRole = userRole;
    }
    public UserLogin(User user, UserRole userRole, String email, String password, Set<LoginSession> loginSessions) {
       this.user = user;
       this.userRole = userRole;
       this.email = email;
       this.password = password;
       this.loginSessions = loginSessions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser_login", unique=true, nullable=false)
    public Integer getIduserLogin() {
        return this.iduserLogin;
    }
    
    public void setIduserLogin(Integer iduserLogin) {
        this.iduserLogin = iduserLogin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role_iduser_role", nullable=false)
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<LoginSession> getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set<LoginSession> loginSessions) {
        this.loginSessions = loginSessions;
    }




}


