package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRoleHasUseCase generated by hbm2java
 */
@Entity
@Table(name="user_role_has_use_case"
    ,catalog="shopping_mall"
)
public class UserRoleHasUseCase  implements java.io.Serializable {


     private Integer userRoleHasUseCaseid;
     private UseCase useCase;
     private UserRole userRole;

    public UserRoleHasUseCase() {
    }

    public UserRoleHasUseCase(UseCase useCase, UserRole userRole) {
       this.useCase = useCase;
       this.userRole = userRole;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_role_has_use_caseid", unique=true, nullable=false)
    public Integer getUserRoleHasUseCaseid() {
        return this.userRoleHasUseCaseid;
    }
    
    public void setUserRoleHasUseCaseid(Integer userRoleHasUseCaseid) {
        this.userRoleHasUseCaseid = userRoleHasUseCaseid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="use_case_iduse_case", nullable=false)
    public UseCase getUseCase() {
        return this.useCase;
    }
    
    public void setUseCase(UseCase useCase) {
        this.useCase = useCase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role_iduser_role", nullable=false)
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }




}


