package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name="wishlist"
    ,catalog="shopping_mall"
)
public class Wishlist  implements java.io.Serializable {


     private Integer idwishlist;
     private User user;
     private Date date;
     private Set<WishlistItems> wishlistItemses = new HashSet<WishlistItems>(0);

    public Wishlist() {
    }

	
    public Wishlist(User user) {
        this.user = user;
    }
    public Wishlist(User user, Date date, Set<WishlistItems> wishlistItemses) {
       this.user = user;
       this.date = date;
       this.wishlistItemses = wishlistItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idwishlist", unique=true, nullable=false)
    public Integer getIdwishlist() {
        return this.idwishlist;
    }
    
    public void setIdwishlist(Integer idwishlist) {
        this.idwishlist = idwishlist;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wishlist")
    public Set<WishlistItems> getWishlistItemses() {
        return this.wishlistItemses;
    }
    
    public void setWishlistItemses(Set<WishlistItems> wishlistItemses) {
        this.wishlistItemses = wishlistItemses;
    }




}


