package DB;
// Generated Feb 15, 2015 2:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WishlistItems generated by hbm2java
 */
@Entity
@Table(name="wishlist_items"
    ,catalog="shopping_mall"
)
public class WishlistItems  implements java.io.Serializable {


     private Integer idWishlistItems;
     private Stock stock;
     private Wishlist wishlist;

    public WishlistItems() {
    }

    public WishlistItems(Stock stock, Wishlist wishlist) {
       this.stock = stock;
       this.wishlist = wishlist;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_wishlist_items", unique=true, nullable=false)
    public Integer getIdWishlistItems() {
        return this.idWishlistItems;
    }
    
    public void setIdWishlistItems(Integer idWishlistItems) {
        this.idWishlistItems = idWishlistItems;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_idstock", nullable=false)
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wishlist_idwishlist", nullable=false)
    public Wishlist getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }




}


